export class Constants {

    public static scales = {
        majorScales: [
            {name:"C", sharpsflats:"none"},
            {name:"G", sharpsflats:"1 sharp"},
            {name:"D", sharpsflats:"2 sharps"},
            {name:"A", sharpsflats:"3 sharps"},
            {name:"E", sharpsflats:"4 sharps"},
            {name:"B", sharpsflats:"5 sharps"},
            {name:"F#", sharpsflats:"6 sharps"},
            {name:"Db", sharpsflats:"5 flats"},
            {name:"Ab", sharpsflats:"4 flats"},
            {name:"Eb", sharpsflats:"3 flats"},
            {name:"Bb", sharpsflats:"2 flats"},
            {name:"F", sharpsflats:"1 flats"}
        ],
        minorScales: [
            {name:"a", sharpsflats:"none"},
            {name:"e", sharpsflats:"1 sharp"},
            {name:"b", sharpsflats:"2 sharps"},
            {name:"f#", sharpsflats:"3 sharps"},
            {name:"c#", sharpsflats:"4 sharps"},
            {name:"g#", sharpsflats:"5 sharps"},
            {name:"eb", sharpsflats:"6 flats"},
            {name:"bb", sharpsflats:"5 flats"},
            {name:"f", sharpsflats:"4 flats"},
            {name:"c", sharpsflats:"3 flats"},
            {name:"g", sharpsflats:"2 flats"},
            {name:"d", sharpsflats:"1 flat"}
        ],
        allScales: [
            {name:"C", sharpsflats:"none"},
            {name:"G", sharpsflats:"1 sharp"},
            {name:"D", sharpsflats:"2 sharps"},
            {name:"A", sharpsflats:"3 sharps"},
            {name:"E", sharpsflats:"4 sharps"},
            {name:"B", sharpsflats:"5 sharps"},
            {name:"F#", sharpsflats:"6 sharps"},
            {name:"Db", sharpsflats:"5 flats"},
            {name:"Ab", sharpsflats:"4 flats"},
            {name:"Eb", sharpsflats:"3 flats"},
            {name:"Bb", sharpsflats:"2 flats"},
            {name:"F", sharpsflats:"1 flats"},
            {name:"a", sharpsflats:"none"},
            {name:"e", sharpsflats:"1 sharp"},
            {name:"b", sharpsflats:"2 sharps"},
            {name:"f#", sharpsflats:"3 sharps"},
            {name:"c#", sharpsflats:"4 sharps"},
            {name:"g#", sharpsflats:"5 sharps"},
            {name:"eb", sharpsflats:"6 flats"},
            {name:"bb", sharpsflats:"5 flats"},
            {name:"f", sharpsflats:"4 flats"},
            {name:"c", sharpsflats:"3 flats"},
            {name:"g", sharpsflats:"2 flats"},
            {name:"d", sharpsflats:"1 flat"}
        ]
    }

    public static metronomeMarkings = [
        {name: "Larghissimo:", description: "very, very slow 24 bpm"},
        {name: "Grave:", description: "very slow (25–45 bpm)"},
        {name: "Largo:", description: "broadly (40–60 bpm)"},
        {name: "Lento:", description: "slowly (45–60 bpm)"},
        {name: "Larghetto:", description: "rather broadly (60–66 bpm)"},
        {name: "Adagio:", description: "slow and stately (literally, 'at ease') (66–76 bpm)"},
        {name: "Adagietto:", description: "slower than andante (72–76 bpm)"},
        {name: "Andante:", description: "at a walking pace (76–108 bpm)"},
        {name: "Andantino:", description:  "slightly faster than Andante (although in some cases it can be taken to mean slightly slower than andante) (80–108 bpm)"},
        {name: "Andante moderato:", description:  "between andante and moderato (thus the name andante moderato) (92–112 bpm)"},
        {name: "Moderato:", description:  "moderately (108–120 bpm)"},
        {name: "Allegretto:", description:  "moderately fast (112–120 bpm)"},
        {name: "Allegro moderato:", description:  "close to but not quite allegro (116–120 bpm)"},
        {name: "Allegro:", description:  "fast, quickly, and bright (120–168 bpm) (molto allegro is slightly faster than allegro, but always in its range)"},
        {name: "Vivace:", description:  "lively and fast (168–176 bpm)"},
        {name: "Vivacissimo:", description:  "very fast and lively (172–176 bpm)"},
        {name: "Allegrissimo or Allegro vivace:", description:  "very fast (172–176 bpm)"},
        {name: "Presto:", description:  "very, very fast (168–200 bpm)"},
        {name: "Prestissimo:", description:  "even faster than Presto (200 bpm and over)"},
    ]
}